### ISSUE TITLE
Error when trying to send an asset that already exists on the remote

### ISSUE THREAD

**Issue by jkobus** [php-translation/symfony-bundle#113]
1. I have new translation keys on my website
2. I use profiler to send them to remote: "Send selected translations to SaaS"
3. I added a few more translation keys and reloaded the website page
4. On profiler page under "missing" i see all keys - even keys that were sent in step 2.
5. I click: Send selected translations to SaaS
6. I see error: Asset already exists called "xxx"

The reason is that bundle does not know that these translations were already sent.
The only way of knowing that is to see if translation exists. 

If asset on the remote exists, but was not translated, it will not be downloaded.

I think about accepting this type of response from SaaS so it will not break the whole process, or - to check if asset already exists and ignore it if it does.

**Comment by Nyholm** [comment]
After we send translations to sass we also need to update the local storage (XLIF). But you are sending untranslated stuff?

It does not seams like there is an error... I agree with you. We should not display it as a "Oh no, this is a catastrophe". If we send things to sass and they already exists the everything should be good, right?

**Comment by jkobus** [comment]
Yes, untranslated. 
If we'll add untranslated asset to local xliff file it will be translated to blank string I guess.

Anyway, some kind of "insert if does not exist" would be enough. Then, the meaning of the button "Send selected translations to SaaS" would be more like "Syn selected translations with SaaS".

**Comment by jkobus** [comment]
Theres also one thing: when you create a new key and view it in the profiler, pressing "sync" will only add it to local xliff file (with "target text" same as the key) without sending it to the SaaS. The only way to send that translation is by using translation:sync command.

**Comment by Nyholm** [comment]
That "sync" button is more "download". Not sure what we want. 

Also, when we press "edit", we do a download before showing anything.

**Comment by jkobus** [comment]
Sync on non-existing-on-remote asset would add it to the translation file without notes about params, while the "Send ...." button below does that.

**Comment by jkobus** [comment]
it looks like you already thought about it:
```
        try {
            // Create asset first
            $this->client->asset()->create($projectKey, $message->getKey());
            $this->client->translations()->create($projectKey, $message->getKey(), $message->getLocale(), $message->getTranslation());
        } catch (AssetConflictException $e) {
            // This is okey
            $isNewAsset = false;
        }
```

but theres a small typo in client:
```
        if ($response->getStatusCode() !== 201) {
            $this->handleErrors($response);
        }

        if ($response->getStatusCode() === 409) {
            throw Exception\Domain\AssetConflictException::create($id);
        }
```

it should be:

```
        if ($response->getStatusCode() === 409) {
            throw Exception\Domain\AssetConflictException::create($id);
        }

        if ($response->getStatusCode() !== 201) {
            $this->handleErrors($response);
        }
```

I'll send a PR tomorrow as this worked for me and all translations were sent successfully.

**Comment by Nyholm** [comment]
Thank you for fixing this issue. 

Ref: https://github.com/FriendsOfApi/localise.biz/pull/22
