### ISSUE TITLE
translation:extract false error and bug

### ISSUE THREAD

**Issue by marcoreni** [php-translation/symfony-bundle#143]
Hello,

I'm trying to use translation:extract in my project. 

The process yields a bunch of errors that shouldn't be there:
a- "Message: Form label is not a scalar string": this error happens when I set `label => false` on my form configuration. According to Symfony documentation, this is the way to disable label settings, so the field should be simply ignored.
b- "Message: Form choice is not an array": this error happens when I use a function that returns an array instead of an array for a `ChoiceType` element. I think the extractor should compute the result of the function and use that to extract the translation items.

**Comment by lsv** [comment]
I have added the [issue](https://github.com/php-translation/extractor/issues/68) to the exctrator project

**Comment by Nyholm** [comment]
Im closing this issue because it already exists in the extractor lib.
