### ISSUE TITLE
Cannot edit translation in Fallback tab on Translation page of Symfony WebProfiler

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/symfony-bundle#150]
Cannot edit or cancel editing of fallback translations, get an error in Chrome Console:
> symfonyProfiler.js:79 Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
>    at saveEditForm (symfonyProfiler.js:79)
>    at HTMLInputElement.onclick (f78a96?panel=translation:1)

Steps to reproduce:
1. Go to the translation tab: http://localhost:8000/_profiler/f78a96?panel=translation
2. Click on "Fallback" tab
3. Press "Edit" and then "Save" or "Cancel"
4. See the error I mentioned

**Comment by ctaverne** [comment]
Hi,

I solved it in this PR: https://github.com/php-translation/symfony-bundle/issues/157

**Comment by bocharsky-bw** [comment]
You probably mean PR: #158

**Comment by ctaverne** [comment]
You're right! thank you.
I was tired. It was late :)

**Comment by Nyholm** [comment]
Awesome. Thank you for reporting this. 

This is closed by #158
