### ISSUE TITLE
"Edit Fallback" doesn't work in profiler

### ISSUE THREAD

**Issue by ctaverne** [php-translation/symfony-bundle#157]
I get the following JS error:

`Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at saveEditForm (symfonyProfiler.js:79)
    at HTMLInputElement.onclick (9bf8c4?panel=translation:1)`

After investigation it is due to variable 'key' generation.

id attribute in html <tr> is generated with including current locale and key in saveEditForm is generated with including fallback source locale.

So, symfonyProfiler.js:79, document.getElementById(key) can't find id because in case of fallback message tab, and contrary to missing transaltions tab, id are differents. So, in that case, Js fails and it stops save process.

**Comment by ctaverne** [comment]
I suggest this PR to solve it: https://github.com/php-translation/symfony-bundle/pull/158

**Comment by Nyholm** [comment]
Closed by #158
