### ISSUE TITLE
Translation:extract error

### ISSUE THREAD

**Issue by ctaverne** [php-translation/symfony-bundle#159]
Hi,

I get the following error when I try to extract:

> console translation:extract app en
> 14:18:54 ERROR     [console] Error thrown while running command "translation:extract app fr". Message: "Notice: Undefined offset: 0" ["error" => Symfony\Component\Debug\Exception\ContextErrorException { …},"command" => "translation:extract app fr","message" => "Notice: Undefined offset: 0"] []
> 
> In FormTypeLabelImplicit.php line 37:
>                                
>   Notice: Undefined offset: 0  
>                                
> 
> translation:extract [--hide-errors] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<configuration>] [<locale>]

**Comment by lsv** [comment]
Could you give your add the source of `FormTypeLabelImplicit.php`

**Comment by Nyholm** [comment]
Are you still getting this issue after you updated to the latest version of extractor and the bundle?

**Comment by Nyholm** [comment]
Any updates here?

**Comment by Nyholm** [comment]
Closing due inactivity. Feel free to comment or reopen the issue
