### ISSUE TITLE
How to deal with domains and loco tags?

### ISSUE THREAD

**Issue by ctaverne** [php-translation/symfony-bundle#160]
Is it possible to map domains with loco tags like with happyr bundle ?

dedicated loco projects to domain is working but I tried:
- mapping domains with tags in loco and all translations are pulled into all translation files (messages.yml, validators.yml and routes.yml) each time I make a synchronize.

translation_adapter_loco:

>     projects:
>         test:
>             api_key: 'xxx'
>             domains: ['messages', 'validators']

I can't find any information in doc.
thanks for your help.

**Comment by pimolo** [comment]
That's going to be fixed by https://github.com/php-translation/loco-adapter/pull/29.

**Comment by Nyholm** [comment]
Thank you @pimolo. I just released 0.7.0 of the loco adapter with this feature.
