### ISSUE TITLE
Unable to find template under Symfony 4

### ISSUE THREAD

**Issue by rpkamp** [php-translation/symfony-bundle#176]
When I install the bundle under Symfony 4 and visit the WebUI I get the error:

```
Unable to find template "TranslationBundle:WebUI:base.html.twig" (looked into: /path/to/my/project/templates, /path/to/my/project/templates, /path/to/my/project/vendor/symfony/twig-bridge/Resources/views/Form) in @Translation/WebUI/show.html.twig at line 1.
```

When I replace the reference to  `TranslationBundle:WebUI:base.html.twig` in the template (`show.html.twig`) with `@Translation/WebUI/base.html.twig` it _does_ work.

Is there any way to get the 'old' (colon) syntax to work again, or does this need a PR replacing the old colon syntax with the newer namespace syntax?

**Comment by rvanlaak** [comment]
@rpkamp  you can see #175 and #169 where this was fixed. If you're okay I'm going to close this for now.

@Nyholm can you tag a patch release, as it seems `latest` is broken now.
