### ISSUE TITLE
Unnecessary option in extract command?

### ISSUE THREAD

**Issue by yellow1912** [php-translation/symfony-bundle#190]
In the ExtractCommand, I see

`->addOption('bundle', 'b', InputOption::VALUE_REQUIRED, 'The bundle you want extract translations from.')`

This option is not used anywhere below, should it be removed?

**Comment by Nyholm** [comment]
Isnt it? It should be optional if I remember correctly. 
It is used in the Trait.

**Comment by yellow1912** [comment]
I see, wouldn't InputOption::VALUE_OPTIONAL make more sense thene? Right now it uses VALUE_REQUIRED

**Comment by yellow1912** [comment]
Got it, let me close this issue. Thank you :)
