### ISSUE TITLE
Invalid translation cache after download command execution (with --cache)

### ISSUE THREAD

**Issue by welcoMattic** [php-translation/symfony-bundle#198]
We (with @damienalexandre and @lyrixx) catch an issue with the [DownloadCommand](https://github.com/php-translation/symfony-bundle/blob/master/Command/DownloadCommand.php).

### Steps to reproduce

- We start with an empty cache.
- We do not have any of our translation files versioned.
- We execute the download command to fetch from Loco (or anywhere else).
- Symfony builds its container with a hardcoded translation files list which do not contains the fresh downloaded files.
- We execute again and again the download command **with `--cache` option**, and Symfony's container will rebuild the translation cache files with the old hardcoded list of files. So it never builds cache with new downloaded files.

### Quick fix

- Run `cache:clear` just after the first download command execution.

### Expected behaviour

After the first run of download command, Symfony's container must be rebuilt with all translation files, to be able to warm-up cache for these files. 

We know that it will be hard to fix this issue because it concerns Symfony's way to build container.

**Comment by damienalexandre** [comment]
We looked deep into Symfony and that will not be easy to solve.

There is a Finder lookup when the container is build:

https://github.com/symfony/symfony/blob/374f6e2353781709356e334665539bc31f2c4e11/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L944-L972

So a translation file added after that will never be warmUp by the Translator, 
and this service definition is inlined so we can't clear it easily.

**Comment by nicolas-grekas** [comment]
Could you please give it a try again with 4.3, and report if this is fixed

**Comment by welcoMattic** [comment]
I'll try later this week with 4.3 :+1:

**Comment by welcoMattic** [comment]
Unfortunately, I can not install php-translation/symfony-bundle on Symfony 4.3, even dev-master, cause of composer.json restriction.

Output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-translation/symfony-bundle dev-master -> satisfiable by php-translation/symfony-bundle[dev-master].
    - php-translation/symfony-bundle dev-master requires symfony/translation ^3.4 || ^4.0,<4.2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by bocharsky-bw** [comment]
Hey @welcoMattic , according to the latest releases that were made after Jul 26 could you give it the second try? Does it still a problem for you?

**Comment by welcoMattic** [comment]
Sorry, I totally forgot about this issue. I'll initiate a reproducer as soon as I can. But if you prefer to close this issue now, waiting my tests, it's ok. If this issue is still relevant I will re-open it later.

**Comment by welcoMattic** [comment]
I just reproduce our steps on a 4.3 project, it seems that this issue is now fixed! :tada:
