### ISSUE TITLE
Is translastion of routes included? 

### ISSUE THREAD

**Issue by ScherlOMatic** [php-translation/symfony-bundle#199]
Hello!

This is not an issue, but I couldn't open a PR for this.

With my previous symfony bundle (jms) I was able to translate my routes for different languages.
/contact = /kontakt = /contacto = etc.

Is there a config for enabling this feature or is it planned?

thx in advance

**Comment by mvrhov** [comment]
IMO, there will be no need for that as the next symfony will support multilingual routes out of the box.

**Comment by ScherlOMatic** [comment]
thx for your reply.

the next symfony you are regarding to is version ...?
is there a link you can send me maybe. i havn't found something using google.

thx

**Comment by bocharsky-bw** [comment]
Yeah, I also interested in it. @mvrhov What version of Symfony are you talking about? Do you have some links to a blog posts / docs about it?

P.S. @ScherlOMatic Look at JMSI18nRoutingBundle, looks like it can help with it: https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/218

**Comment by novecode** [comment]
@bocharsky-bw,@ScherlOMatic i18n routing will be included in 4.1 version. You can follow the PR progress here: https://github.com/symfony/symfony/pull/26143

**Comment by mvrhov** [comment]
There is a proposition for router to support translations in different locales. It might be part of 4.1 symfony/symfony#26143

**Comment by rpkamp** [comment]
Symfony 4.1 is here now and translatable routes are part of it https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing

I think this ticket can be closed.

**Comment by odolbeau** [comment]
As suggested by @rpkamp, I close this ticket.
Sorry @picks44 but I'm afraid adding this feature only for Symfony 3.x requires too much work. :/
