### ISSUE TITLE
always_populate_raw_post_data error on webUi with php5.6

### ISSUE THREAD

**Issue by juju95** [php-translation/symfony-bundle#206]
Hi, 

I'm using your bundle for severals project, and i'm seeing on a project on php5.6 that i can't edit / add translation with the WebUi, i have an error about session headers already sent to response.
If i check the ajax call, effectivly, i have these few deprecated lines at top of the edit calls : 

`<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
`
I have the problem only on webUi edit part, Profiler edit is working fine and i don't have it on any other route of the app.
I can't find where is coming from this problem as the tracelog is not helping with it :s and i can't modify the php.ini to disable this deprecating warning

Anybody else has this problem too ? 

Thanks in advance

**Comment by bocharsky-bw** [comment]
I assume this error from PHP itself. If you don't have access to php.ini to set it properly - as a workaround, I think you can use [ini_set()](http://php.net/manual/de/function.ini-set.php) PHP function to set `always_populate_raw_post_data` to `-1` in PHP files

**Comment by Nyholm** [comment]
@juju95, did Victor's fix work for you?
