### ISSUE TITLE
[EditInPlace] Untranslatable messages

### ISSUE THREAD

**Issue by denrique88** [php-translation/symfony-bundle#209]
I'm adding php-translation symfony bundle to an existing application with EditInPlace.

I have some problems editing the translations in buttons.
In a twig, this code doesn't permit me to edit the translation :
``<button class="btn" id="btnReset">{{ 'myapp.core.button.reset'|trans }}</button>``

Moreover, in this application, some translations are done in the controllers. How can I find a way to edit this translations with EditInPlace ? I know I can edit them with WebUI but that would be nice to edit them directly in the webpage.

**Comment by rvanlaak** [comment]
`EditInPlace` relies on the content of a response, so for controller translations the `profiler` or Web UI is the only option.

**Comment by denrique88** [comment]
I think that it may be possible to override trans() function of Translator service, so the trans() function called in controllers would return the translation with the <x-trans ...> tag ? 

Then, EditIInPlace may be able to edit the translation ?

**Comment by rvanlaak** [comment]
Unfortunately, if `->trans` would return ` <x-trans ...>` , the view would eventually always escape that which makes it impossible for `EditInPlace` to allow translation.

**Comment by denrique88** [comment]
Yes, you're right. I intented to do it and EditInPlace just put it as untranslatable with the forbidden icons. I thought that someone would have an idea to do this. ;-)

And what about the buttons ?

**Comment by rvanlaak** [comment]
You can decorate `translator` so it will return `<x-trans ...>`, but then you have to make sure the output is marked as safe by Twig so it does not -by default- escape these tags. The `EditInPlaceResponseListener` then will be able to do the rest.

**Comment by denrique88** [comment]
I did it and I can now edit the translations done in the controllers and js. Some translations are still not editable : some titles, buttons. But it impoved really the functionnality.

Thank you for your answers !

**Comment by rvanlaak** [comment]
Are you open for filing a PR with that improvement?

**Comment by denrique88** [comment]
What is a PR ? I didn't change anything in php-translation bundle but only in my application and the way I used translator services.
