### ISSUE TITLE
[Config] - no way to set custom dumper

### ISSUE THREAD

**Issue by SinSquare** [php-translation/symfony-bundle#231]
Hi,

I'm using a custom translation loader and a custom dumper (to load and save to the database), but I can not set the custom dumper to the 'output_format' configuration.

The following change to the Translation\Bundle\DependencyInjection\Configuration class whould allow it:
from 
`->enumNode('output_format')->values(['php', 'yml', 'xlf', 'po'])->defaultValue('xlf')->end()`
to 
`->scalarNode('output_format')->defaultValue('xlf')->end()`

**Comment by Nyholm** [comment]
Hey. 
You are correct. 
Could you make a PR with that change?

**Comment by odolbeau** [comment]
Fixed by #339
