### ISSUE TITLE
'help' field extractor for Symfony 4.1

### ISSUE THREAD

**Issue by db306** [php-translation/symfony-bundle#234]
Since the release of 4.1, a new field is now available for forms.

```
->add('username', TextType::class, array (
                'label' => 'user.form.username',
		'help' => 'form.user.password.help',
                'translation_domain' => 'form'
            ))
```
These have not been implemented yet in the php-translation bundle
should we build a custom extractor for it?

**Comment by Nyholm** [comment]
@odolbeau made a PR to the extractor to fix this issue. Thank you for reporting this.
