### ISSUE TITLE
Unknown "xxx" function.

### ISSUE THREAD

**Issue by tristanbes** [php-translation/symfony-bundle#245]
Hello,

Running the extraction command gives errors
`Unknown "inheritance_helper" function.`

the `inheritance_helper` is a `\Twig_SimpleFunction` registered in a `\TwigExtension`, so I don't understand why it gives me this error.

Do you have any ideas ?

**Comment by tristanbes** [comment]
Sorry. This is a double kernel application and the extension wasn't enabled in the other kernel :-)

**Comment by Nyholm** [comment]
Hm. What twig version are you running? I do recognize that function call. Where is it called?

**Comment by Nyholm** [comment]
Okey. Thank you for getting back.
