### ISSUE TITLE
Dependency error immediatly after installation

### ISSUE THREAD

**Issue by pawellen** [php-translation/symfony-bundle#249]
After doing steps in this doc:
1) Install Via Composer
2) Add example configuration
3) Can't clear cache, because I always get error (in app_dev.php and in CLI)
The service "profiler" has a dependency on a non-existent service "php_translation.data_collector".

After I tried to disable profiler in config, I got next depenedcency error:
The service "php_translation.catalogue_fetcher" has a dependency on a non-existent service "translation.loader_or_reader"

and so on and on...

Versions:
"symfony/symfony": "3.4.*",
"symfony/translation": "^4.1",
"php-translation/symfony-bundle": "^0.8.0",

**Comment by brizzz** [comment]
To fix that enable translator component in symfony configuration:

`framework: translator: { fallbacks: [en] }`

https://symfony.com/doc/3.4/translation.html#configuration

**Comment by odolbeau** [comment]
Looks like this issue is solved, don't hesitate to open a new one if needed.
