### ISSUE TITLE
Extracted message ID's are incorrect (symfony 4?)

### ISSUE THREAD

**Issue by Mondane** [php-translation/symfony-bundle#254]
For forms, the extracted ID's are all lowercase but symfony wants it camelcase:

FormType:
```php
<?php
namespace App\Form;

use App\Entity\ContactMessage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactMessageType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('subject', null, ['required' => false])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => ContactMessage::class,
        ));
    }
}
```

The extraction:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:2.0" version="2.0" srcLang="nl" trgLang="nl">
  <file id="messages.nl">
    <unit id="qUkfTBv" name="subject">
      <notes>
        <note category="file-source" priority="1">src/Form/ContactMessageType.php:15</note>
        <note category="state" priority="1">new</note>
      </notes>
      <segment>
        <source>subject</source>
        <target></target>
      </segment>
    </unit>
  </file>
</xliff>
```

But wanted by symfony:
![image](https://user-images.githubusercontent.com/1150272/44082101-a20eb71c-9fb0-11e8-927e-fc650cd4dc34.png)

The same holds true for any other form field.

**Comment by Mondane** [comment]
NB If the name field name is camelCased, the message ID asked by symfony becomes 'Camel cased'.

**Comment by welcoMattic** [comment]
@Mondane is there any updates here? Is this bug still relevant?

**Comment by rmbl** [comment]
Yes, this is still relevant. I've got the same problem on a new application using Symfony 5.0. Symfony seems to run FormRenderer::humanize over the label if the label is not explicitly set.

I fixed it for myself in https://github.com/php-translation/extractor/pull/154. Don't know if that would work for the library as a whole.
