### ISSUE TITLE
Update Cache after Sync in prod environment

### ISSUE THREAD

**Issue by poohia** [php-translation/symfony-bundle#267]
Hello I use https://github.com/php-translation/loco-adapter for sync with my SaaS software.
I need to do update cache of production environment when "translation:sync" command detecting any changing translations without clear cache in all call of synchronisations .

How I do that ?

**Comment by albingi** [comment]
You can use the "translation:download --cache" command.

**Comment by tony-tran** [comment]
Hi, 

I have the same problem
I use `translation:download -n --cache` to have the new translation. But the cache is never clear so I have always the old version on front.

**Comment by bocharsky-bw** [comment]
@tony-tran Have you tried to run `bin/console cache:clear` after `bin/console translation:download` commands? Does it fix the problem for you?

**Comment by nicolas-grekas** [comment]
Same as https://github.com/php-translation/symfony-bundle/issues/198?

**Comment by odolbeau** [comment]
Duplicate issue as spotted by @nicolas-grekas
