### ISSUE TITLE
Add support for IntlMessageFormatter 

### ISSUE THREAD

**Issue by welcoMattic** [php-translation/symfony-bundle#269]
In anticipation of Symfony 4.2 release, we should work on support of the new `IntlMessageFormatter`

See [https://symfony.com/blog/new-in-symfony-4-2-intlmessageformatter](https://symfony.com/blog/new-in-symfony-4-2-intlmessageformatter)

I'm looking for all changes involved by this new Formatter

**Comment by Nyholm** [comment]
What is needed from the bundle's side to support this?

**Comment by welcoMattic** [comment]
I totally forgot that I opened this issue over a year ago. I'm sorry. 
I'll get back to it and figure out what we need to do to support IntlMessageFormatter as soon as I can.

**Comment by odolbeau** [comment]
I'm already using this format in my app & everything looks fine, even if I didn't try to use a translation as complicated as the one given in the example.

**Comment by welcoMattic** [comment]
As I see, and test in a real life application, there's nothing to do to support this format but improve Profiler message editor (which is a dead simple textarea). May be we should look around https://format-message.github.io/icu-message-format-for-translators/editor.html?

**Comment by bocharsky-bw** [comment]
Should be fixed in #452
