### ISSUE TITLE
Locale not in project

### ISSUE THREAD

**Issue by next-sentence** [php-translation/symfony-bundle#282]
Hello, I am using this this bundle in a symfony 4 application with loco-adapter.
This worked fine until I added a few new locales in localise as well as in my config file,
and when trying to sync 
"php bin/console translation:sync app down"
I'm getting an API exception: "Locale not in project".
Any suggestions what I'm doing wrong?

![image](https://user-images.githubusercontent.com/8638853/52797317-49949e80-307e-11e9-9190-858ca822303a.png)

![image](https://user-images.githubusercontent.com/8638853/52797364-66c96d00-307e-11e9-949c-edf221b357c1.png)

**Comment by bocharsky-bw** [comment]
Hm, have you tried to clear the cache before running `bin/console translation:sync app down`?

**Comment by next-sentence** [comment]
Already fixed, the problem was with localise API key, it worked only after regeneration.
Thanks!

**Comment by bocharsky-bw** [comment]
Thank you for sharing your solution with others 👍
