### ISSUE TITLE
excluded_dirs in config matches filenames too

### ISSUE THREAD

**Issue by Nils-1st-retail** [php-translation/symfony-bundle#284]
Hi
I just noticed that the values in ‘excluded_dirs’ in the config doesn’t only match in directories but matches files names too, and the values are matched with a wildcard ending. 

I have a project with a file called “dataSelection.html.twig”, and a folder called “dataDisplay”
Both the folder, and the file is ignored as soon a the ‘excluded_dirs’ contain the value ‘data’.

My expectation would be that only the directory ‘data’ would be ignored since there’s no wildcards lithe in the ‘excluded_names’, and that the value would only match on directories not files. 

For now I have just removed the values in the ‘excluded_dirs‘ to get all my translations extracted.

**Comment by seizan8** [comment]
Yeah. I had pretty much the same error.

Some of our translations were missing, not being extracted correctly and we did not understand why.
The missing translations were in a file called "base_data"...
