### ISSUE TITLE
Compatibility issue with Twig 2.7.0+

### ISSUE THREAD

**Issue by Kocal** [php-translation/symfony-bundle#288]
Hi,

I wanted to update Twig from 2.6.2 to 2.7.0 because of a security issue:
![Sélection_383](https://user-images.githubusercontent.com/2103975/54205712-28856900-44d7-11e9-9b61-47718b18f864.png)

However, I'm facing a compatibility issue:
![Sélection_382](https://user-images.githubusercontent.com/2103975/54205715-28856900-44d7-11e9-9b40-11f812e41c65.png)

Since Twig 2.7.0, they don't use class aliases anymore (e.g.: `Twig_Environment`) but class namespaces (e.g. `Twig\Environment`) directly, refs:
  - https://symfony.com/blog/new-in-twig-namespaced-classes
  - https://github.com/twigphp/Twig/pull/2863
  - https://github.com/twigphp/Twig/pull/2869
  - [changelog](https://github.com/twigphp/Twig/blob/2fe2f2d8bba055f78657b81d01ed588fd22d8cd3/CHANGELOG#L23)

I tried to fork and replace class aliases by class namespaces, but it's out of my scope. 
I don't have the time to do it, I don't know about your breaking changes policy, I don't know if I should update the `.travis.yml` to use a specific version of Twig... :confused: 

Thanks!

**Comment by Kocal** [comment]
Also, someone opened an issue about this on the Twig repo: https://github.com/twigphp/Twig/issues/2886

So maybe we will have nothing to upgrade here

**Comment by mdeboer** [comment]
@Kocal I checked the dependencies and as far as I can tell, it's safe to use namespaced classes instead of class aliases.

Even though the referenced issue and PR might solve the issue for now, why not make sure it does not happen again. Getting rid of the trickery involved with aliases.

**Comment by Kocal** [comment]
Well, in fact it's fixed by https://github.com/twigphp/Twig/pull/2887

So I'm closing this one :)

**Comment by stof** [comment]
Migrating to namespaced Twig classes might still be a good idea though, as Twig 3.x will remove non-namespaced classes.

**Comment by Kocal** [comment]
Yep of course!

**Comment by Kocal** [comment]
I opened a PR (#290) which replace Twig aliases.
