### ISSUE TITLE
Symfony Profiler UI improvements

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/symfony-bundle#296]
Bundle shows "Add selected messages" button and checkboxes next to translations but checkboxes are inactive and this "Add selected messages" button works only for "Missing" tab:
 
<img width="1061" alt="Screen Shot 2019-03-13 at 17 13 29" src="https://user-images.githubusercontent.com/3317635/54290304-65269280-45b3-11e9-8521-a573b73eb569.png">

I think it would be better to hide checkboxes and "Add selected messages" button at all on "Defined" and "Fallback" tabs. We really need it only on "Missing" tab. It would mislead users less.

**Comment by odolbeau** [comment]
Fixed by #371
