### ISSUE TITLE
Incomplete documentation. No way to specify dumper in config

### ISSUE THREAD

**Issue by faizanakram99** [php-translation/symfony-bundle#301]
I get this error when saving translation via web ui with Symfony 3.4 standard edition

message: "There is no dumper associated with format "xliff".

Documentation says nothing about dumper.

Is there no way to specify Dumper in config, if there is not, it should be mentioned explicitly in docs how to add a dumper.

For now, I just overrode the service definition

```
translation.writer:
        class:     Symfony\Component\Translation\Writer\TranslationWriter
        public:    true
        calls:
            - [addDumper, ['xliff', '@translation.dumper.xliff']]
```

**Comment by odolbeau** [comment]
Hi @faizanakram99 
Sorry for the delay. :(

The `translation.writer` is a service declared by Symfony directly and is not part of this bundle.
We obviously use it to export translations when asked and the `translation.writer` will automatically used configured dumper.

I close this PR but keep #302 open for now
