### ISSUE TITLE
Meta issue about failed tests on TravisCI

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/symfony-bundle#305]
All our TravisCI builds are red lately due to deprecations, PHP strict types, or new features in related packages. But we have some separate open PRs that are trying to fix separate failures - it would be good to merge them first. Let me list all of them here:

- Bump to Symfony 3.4 and PHP 7.1 #277
- chore(travis): disable Composer's memory limit #291
- chore(twig): replace class aliases by class namespaces #290
- Fix tests: Pass empty string instead NULL as the 2nd arg to Source #304

Or probably we should ignore deprecations in tests? Because if I understand it correctly, some of them are from third-party bundles, so we can't fix them here and TravisCI would be red until it wasn't fixed upstream.

We also have several PRs with minor tweaks/fixes that easily could be merged but due to red TravisCI I think nobody can merge it except @Nyholm , so make tests green here would be very cool.

**Comment by Nyholm** [comment]
Thank you. 

All these issues are merged and tests are green. 
I've also promoted you to admin =)

**Comment by bocharsky-bw** [comment]
@Nyholm Thank you :)
