### ISSUE TITLE
A translation multiple times on same page

### ISSUE THREAD

**Issue by codreanulaurentiu** [php-translation/symfony-bundle#306]
If you have the same translation key multiple times in a page, the EditInPlace feature won't work, since it won't modify all the entries of the translations.

Steps to reproduce:
1. Go on a page where the same key is present in multiple elements.
2. Edit one of the keys.
3. Press the save button.

Expected behaviour: Change translations.

Actual behaviour: nothing happens.

**Comment by bocharsky-bw** [comment]
Hm, it seems like an edge case. I'd not recommend you reusing translation keys: neither on one page, not in whole project. Even if translation messages ARE the same - just use different keys for them. Tobias talks about it on conferences

**Comment by codreanulaurentiu** [comment]
@bocharsky-bw so basically what you're saying is, if my user has text "A" on page 1, and he edits that text, he should then go on page 2, to edit the same text "A". Also, having unique messages on an app having >40k messages is unrealistic to me. But that's just my 2 cents. If you don't see this is as an issue, we can close it.

**Comment by rvanlaak** [comment]
There are some cases where keys could be reusable, but in the scenario you describe in your comment I would advise to make new keys. Not reusing translation keys is the best practice.

https://php-translation.readthedocs.io/en/latest/best-practice/

> If you have the same translation key multiple times in a page, the EditInPlace feature won't work, since it won't modify all the entries of the translations.

What you're saying in the PR description is that two translations of one key on a single page do not change after edit. That differs from what you're describing in the last comment. I would mark this as enhancement, as refreshing would show the new key.
