### ISSUE TITLE
Is this bundle abadoned?

### ISSUE THREAD

**Issue by NullIsNot0** [php-translation/symfony-bundle#308]
I migrated to Symfony 4.3 and translation editing in profiler is not loaded. I found out theat it needs block name change in file `Resources/views/SymfonyProfiler/translation.html.twig` line 9 from `{% block panelContent %}` to `{% block panel %}`.
Do I need to create a pull request? Will it be merged? As I see there are lot of unmerged PR, and it leads me to thinking that this bundle is abadoned :(

**Comment by Aerendir** [comment]
I hope it isn't 😅Waiting for answers from someone more involved...

**Comment by bocharsky-bw** [comment]
I think it's not :) // ping @Nyholm

**Comment by Nyholm** [comment]
No, it is not. But yes. We should probably make a session to clean up open PRs and issues.

**Comment by bobdenotter** [comment]
I've bumped into this same issue. Hope it will get resolved soon. 👍

**Comment by NullIsNot0** [comment]
If someone else is finding this issue, you can use package `nullisnot0/symfony-translation-bundle`. I have forked `php-translation/symfony-bundle` v0.8.1 and added modifications mentioned in first comment of this issue.
Note that package `nullisnot0/symfony-translation-bundle` is only for Symfony 4.3.
I will continue to use `php-translation/symfony-bundle` after it will be fixed, but for now I can't, because it's not compatible with Symfony 4.3.

**Comment by Nyholm** [comment]
Hey @NullIsNot0 You should help us spark some life back here. Do you want to be invited to the maintaining team?

**Comment by NullIsNot0** [comment]
@Nyholm, I have very little expirience in collaborating with other devs, if I can be useful in moving this project forward (under someones supervision), I can contribute some time.

**Comment by bocharsky-bw** [comment]
Looks like it was fixed in #311 guys, feel free to give a code review who interested in it, thanks!

**Comment by Nyholm** [comment]
Okey. Let's learn as we go. There are only two rules: 
- Always always always follow [Semver](https://semver.org/)
- Dont merge your own PRs without review. (Exceptions could be made, ie it is a small PR and you dont get any response for a week even though you asked for it)

I had this repo on my TOOD list for the past two weeks without never really gotten around to it.

**Comment by XWB** [comment]
@Nyholm I would like to volunteer as well. I'm maintaining some FriendsOfSymfony bundles and know my way around.

**Comment by odolbeau** [comment]
I'm also available to help a bit on this bundle if needed!

**Comment by welcoMattic** [comment]
As I already contribute to php-translation organization, I'm also available to help as much as I can! :wink:

**Comment by bocharsky-bw** [comment]
New PRs and PRs reviews are always warmly welcome here! If anyone has an availability - please, feel free to work on this repository and help to push it forward.

Cheers!

**Comment by welcoMattic** [comment]
@bocharsky-bw I just reviewed the 11 opened PRs. Many of them are blocked because of red tests that probably could be fixed byfixing and merging this PR https://github.com/php-translation/symfony-bundle/pull/277. May be @Nyholm could help us to fix this one, then we will move on with other PRs?

Thanks!

**Comment by bocharsky-bw** [comment]
Tests in `master` were fixed by me, so most probably PRs should be just rebased with the latest changes in master to pass. Though #277 contains good changes

**Comment by Nyholm** [comment]
Awesome. I will put in some work this weekend. Sorry for the replay

**Comment by Nyholm** [comment]
Im super happy with everyone volunteering. You got an invite!
Master is green. A few PRs are merged. Please continue reviewing and submitting PRs. 

I will close this issue now. 

Thank you <3
