### ISSUE TITLE
[Question/Suggestion] Allows you to specify a project to the sync command

### ISSUE THREAD

**Issue by mmarchois** [php-translation/symfony-bundle#326]
Hi,

I use https://github.com/php-translation/loco-adapter for sync translations. I have many projects and they are all synchronized when I launch the sync command.
Is there a way to specify a project ?
For example `bin/console translation:sync default down --project=myLocoProject`.

**Comment by hhamon** [comment]
:+1: 

Experiencing the same on my project. At Dayuse.com, we deal with ~12 different languages and 3 Loco projects (more will be added soon). When syncing translations from Loco, it takes an average of 2 minutes to download and update files. However we often just update one Loco project, so it would be more convenient if we could selectively tell the command to update one (or more) projects.

```
bin/console translation:sync default down --project=myLocoProject --project=myOtherLocoProject
```

To go further, it would be even nicer to selectively update certain project and locales:

```
bin/console translation:sync default down --project=myLocoProject --project=myOtherLocoProject --locale=fr --locale=th-TH
```

**Comment by welcoMattic** [comment]
Hi!

The idea looks great, if you want to start a PR, your are welcome. For the moment we are focusing on stabilizing the bundle and make it compatible with Symfony > 4.2, but be sure we get interest on this idea :+1:

**Comment by Nyholm** [comment]
Im digging this up again. 
It was more complicated that I first thought last time I looked at it. Now Im not sure... So, If we start bottom up looking at the loco adapter and the API docs:

- https://github.com/php-translation/loco-adapter/blob/0.10.0/src/Loco.php#L165-L190
- https://localise.biz/api/docs/export/exportlocale

The `TransferableStorage::export()` now has an option parameter that allows us to support all kind of arbitrary data. So my idea was to look at the API docs, find a few parameters that we like, then use the `$options` array to set those parameters. 

-------

Starting top down, 
The `SyncCommand` gets a `StroageService` which is configured with a lot of remote and local storages. We call `StroageService::sync()` function, which calls `StroageService::mergeDown()` which calls `StroageService::download()´. The download function calls `TransferableStorage::export()`. 

I will work on a PR which allows you to send arbitrary data with the `sync` command. @mmarchois  or @hhamon, could you send a PR to the Loco adapter which looks inside the `$options` array to find options it supports and pass it on to the API?

**Comment by Nyholm** [comment]
Here is the PR: 378
