### ISSUE TITLE
Method getRawData has been removed, but still has usage

### ISSUE THREAD

**Issue by rvanlaak** [php-translation/symfony-bundle#343]
On line 300 the method  `getRawData` is called, but it has been removed in var-dumper v4.0

Found it by running phpstan on level 2. Should the call get removed? Can it get replaced with `\Symfony\Component\VarDumper\Cloner\Data::getValue`?

https://github.com/php-translation/symfony-bundle/blob/c21280df3d959bd0190c31c982f89c57c52d247b/Model/SfProfilerMessage.php#L295-L303

see [var-dumper changelog](https://github.com/symfony/var-dumper/blob/master/CHANGELOG.md#400)

**Comment by odolbeau** [comment]
I don't get it, how is it possible to have a parameter which is an instance of `Symfony\Component\VarDumper\Cloner\Data`?

**Comment by Nyholm** [comment]
> I don't get it, how is it possible to ...

$this->parameters is an array, we are looping over its elements. 

> Can it get replaced with \Symfony\Component\VarDumper\Cloner\Data::getValue?

I dont know. I dont remember what the difference were... Try to see if anything breaks =)

**Comment by odolbeau** [comment]
Fixed by #342
