### ISSUE TITLE
Flex recipe looking for .yml files instead of .yaml files for routing

### ISSUE THREAD

**Issue by hisem** [php-translation/symfony-bundle#380]
Hi,

I tried to install this bundle using `composer require php-translation/symfony-bundle` on a symfony5 project.
On the subsequent cache clear, I got the following error:

> Unable to find file "@TranslationBundle/Resources/config/routing_webui.yml" in @TranslationBundle/Resources/config/routing_webui.yml (which is being imported from "[project_path]/config/routes/dev/php_translation.yaml"). Make sure the "TranslationBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@TranslationBundle/Resources/config/routing_webui.yml" is not empty.

It took me awhile to realise it was looking for `routing_webui.yml` instead of `routing_webui.yaml` which is the correct extension of the file in the bundle.

This is probably due to the recent #362 merge

I simply changed the pre-configured route paths and all works well.

Could the flex recipe be out of date?

Many thanks

**Comment by odolbeau** [comment]
Hi @hisem!

You're totally write.
A PR have been created a few weeks ago on `symfony/recipes`:
https://github.com/symfony/recipes-contrib/pull/814

**Comment by hisem** [comment]
@odolbeau Oh perfect, thank you ! :) 

Do changes to recipes take a long time to be merged? That PR seems to have been validated 15 days ago.

**Comment by welcoMattic** [comment]
@odolbeau do you know who we can ping to merge https://github.com/symfony/recipes-contrib/pull/814 ?

**Comment by odolbeau** [comment]
Nope... It looks like everything is OK on this PR, I don't why is not merged yet... :thinking:

**Comment by rvanlaak** [comment]
Was merged 1 hr ago 👍 

https://github.com/symfony/recipes-contrib/pull/814#event-2942404362
