### ISSUE TITLE
[DX] Automatically expend parameters when cliking on "show parameters"

### ISSUE THREAD

**Issue by lyrixx** [php-translation/symfony-bundle#389]
ATM, we need 2 clicks to show the parameters.
It would be awesome if only one click would be required

![php translation](https://user-images.githubusercontent.com/408368/72604219-bfeaf200-391a-11ea-95c5-9eb32c1b314f.gif)

**Comment by lyrixx** [comment]
I don't use this bundle anymore, and I don't have to time to contribute. 

So I'm closing this issue. Thanks

**Comment by rvanlaak** [comment]
Was the fact that Symfony adopted quite some of the translation related code in core the reason for you to not use this bundle anymore in the project you are refering to?

**Comment by lyrixx** [comment]
Actually, the project where I used this bundle is not maintened anymore
