### ISSUE TITLE
JsTranslation & cacheClearer

### ISSUE THREAD

**Issue by victor-paumier** [php-translation/symfony-bundle#397]
Hi,

I am currently implementing this bundle with Loco as external storage, and glad to see how easy it is to set-it up!
Beside of that, I also use [BazingaJsTranslationBundle](https://github.com/willdurand/BazingaJsTranslationBundle) to manage Js translations. 
As this bundle also requires to clear the cache after any changes, I wanted to merge both cache clear process. Then I tried to do it by overriding the CacheClearer service, but as this service is declared as a final class, I can't do it this way.
So, is there any way to achieve that currently? Or could creating a CacheClearerInterface be a possible solution?

Thanks

**Comment by victor-paumier** [comment]
nevermind, I finally override the download command

**Comment by rvanlaak** [comment]
Feel free to draft a PR if you want some additional feedback, or when it would enhance the existing command 👍

**Comment by victor-paumier** [comment]
I am ok to create serviceInterfaces if it's ok for you, but:
- is that a good way to do it? Or may we think about removing the final keyword on services instead?
- where should I create them? (/Model/CacheClearerInterface? /Service/CacheClearerInterface? Somewhere else?)
- do we want all services to be overridable or only some of them?

**Comment by rvanlaak** [comment]
Enhancing the implementation for your use case would be possible by [decorating the service](https://symfony.com/doc/current/service_container/service_decoration.html) (instead of extending). That way there is no option to leak abstraction as the `final` behavior is respected.

You mention your use case is clearing the cache. Does your implementation require any behavior that isn't available via the public interface of the class? Is making use of the service not sufficient?

**Comment by victor-paumier** [comment]
I agree that decorating the service is really helpful! 
But even if I decorate the cacheClearer service, I also have to override the download command only to correcting the service class path even if I don't really have to modify it.

I was also working on a solution in order to being able to translate entities implementing Gedmo\Translatable in the same place than the website translation. I ended up creating a custom local storage. Regarding that, I could work on a dedicated bundle if that interest someone?

Last question, why is the mergeUp function based on the translations files instead of being based on the local storages? Shouldn't it use a download function equivalent for local storages instead?
