### ISSUE TITLE
Extract with annotation @Translate

### ISSUE THREAD

**Issue by pdias** [php-translation/symfony-bundle#402]
I try to translate some labels… using annotation.

```
$builder->add(
            'photoFile',
            VichFileType::class,
            [
                'required' => false,
                'allow_delete' => true, // not mandatory, default is true
                'download_uri' => true, // not mandatory, default is true
                'label' => 'user.photo',
                'help' => 'user.photo.help',
                'help_attr' => ['class' => 'mt-0'],
                'delete_label' => /** @Translate */'user.photo.remove',
                'download_label' => /** @Translate */'user.photo.download',
                'attr' => [
                    'placeholder' => 'user.photo.placeholder',
                    'lang' => $this->locale,
                    'class' => 'btn-light',
                    'accept' => 'image/jpg, image/jpeg, image/png',
                ],
                'translation_domain' => 'My',
            ]
        );
```

But `'delete_label' => /** @Translate */'user.photo.remove'` and ` 'download_label' => /** @Translate */'user.photo.download'` are not extracted. Maybe I'm doing something wrong, but I don't understand what.

**Comment by axi** [comment]
have you included 
`use Translation\Extractor\Annotation\Translate;`
?

**Comment by pdias** [comment]
Yes.

**Comment by jeremiegrenier** [comment]
Hello,

I got the same problem. I installed the bundle. Add annotation over the key trad I want to be extracted:

`
new Metas(
      'mission_oid',
      /* @Translate({"domain"="toto"}) */
      'document_metas_oid'
 );
 `
 
 I tried to put a trans over to see if the files is parsed :
 

`
$this->translator->trans('test');

new Metas(
      'mission_oid',
      /* @Translate({"domain"="toto"}) */
      'document_metas_oid'
 );`
 
 
 And the 'test' trad key was extracted.
 
 Did anyone know how to fix the annotation ?
