### ISSUE TITLE
Illegal constructor in editInPlace.js at lines 11 and 19

### ISSUE THREAD

**Issue by dubitoph** [php-translation/symfony-bundle#409]
After the installation of the bundle and the configuration to use Edit in Place, I get this error : 

![Capture](https://user-images.githubusercontent.com/47710530/75865951-9ae80b00-5e04-11ea-889d-a1d536679112.JPG)

I use XLIFF format for my translation files.

**Comment by kadiiskiFFW** [comment]
Hello, any updates here?

**Comment by rvanlaak** [comment]
Did you run `bin/console asset:install`?

**Comment by kadiiskiFFW** [comment]
Yes, at least I did.

**Comment by gimler** [comment]
i get the same error also using xliff on error entry for every twig trans call
Uncaught TypeError: Illegal constructor.
    Choo 2
editInPlace.js:11:24
![image](https://user-images.githubusercontent.com/200904/108071525-1d91c680-7066-11eb-9b1b-a573eba9f0ed.png)

![image](https://user-images.githubusercontent.com/200904/108071583-313d2d00-7066-11eb-8a41-80239e961231.png)
