### ISSUE TITLE
Interface Translation\Common\Storage not found

### ISSUE THREAD

**Issue by Ciloe** [php-translation/symfony-bundle#414]
Hi ! 

I have this error with the version `"php-translation/symfony-bundle": "^0.12",`. You can see it in this file : 

`/var/www/symfony/vendor/php-translation/symfony-bundle/Service/StorageService.php:28`
```php
// Some codes
use Translation\Common\Storage;
// Some Uses

final class StorageService implements Storage 
{
// Somme codes
}
```

But the interface Storage does not exist. You nee to use `StorageInterface`

**Comment by Ciloe** [comment]
For more details, this is the lines on the composer install : 
```
  - Installing php-translation/common (dev-master 5dd7ca8): Loading from cache
  - Installing php-translation/extractor (dev-master 0bf5b83): Loading from cache
  - Installing php-translation/symfony-storage (dev-master 9d6e34d): Loading from cache
  - Installing php-translation/symfony-bundle (dev-master 549cc8b): Loading from cache
```

**Comment by odolbeau** [comment]
Hi @Ciloe!
It looks like you're using `dev-master` version of all repositories, that's why this is not working. :)

**Comment by Ciloe** [comment]
I fixed it with adding the common version in my composer
```
        "php-translation/common": "3.0.1",
        "php-translation/symfony-bundle": "0.12",
```
