### ISSUE TITLE
Standalone Symfony Translation integration

### ISSUE THREAD

**Issue by s7anley** [php-translation/symfony-bundle#415]
Hi 👋 

Did you consider separating integration for non-symfony applications, which are using some Symfony components? 

We started to use php-translation in our Symfony application, but now we want to also integrate php-translation to our legacy application so we use the same translation flow for all applications.

I'm talking about Catalogue, Command, Service and Model namespace as a baseline, maybe also FallbackTranslator?

What do you think?

Thanks!

**Comment by welcoMattic** [comment]
Hello!

As we are working on integrate many of features of this bundle directly into Symfony, I don't think we are going to separate the logic into non-symfony package, sorry.

But feel free to get inspiration of our work to build your own package if needed!

Thanks for your comment

**Comment by s7anley** [comment]
Oh, that's shame, but I understand that it would complicate the things for you guys. I already did the own package for testing purposes, so I will continue with it.

Thanks!

**Comment by rvanlaak** [comment]
@welcoMattic the discussion on which components could get moved to Symfony vs. to other `php-translation` repos would be an interesting one though 👍

**Comment by s7anley** [comment]
I will let you know once I'm done with integration in our legacy application.
