### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by idybil** [php-translation/symfony-bundle#423]
Cannot install on PHP 8, is it in your plan to support PHP 8 soon ?

Message from composer : 
php-translation/symfony-bundle[dev-master, 0.12.1] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.

Thanks

**Comment by lepiaf** [comment]
Hello,

For information, I've opened multiple PR to add support for PHP 8
- https://github.com/php-translation/loco-adapter/pull/56
- https://github.com/php-translation/extractor/pull/157
- https://github.com/php-translation/symfony-storage/pull/51
- https://github.com/php-translation/common/pull/40

**Comment by Nyholm** [comment]
Awesome. These 4 libraries are released. Im working on a release for the bundle now.

**Comment by idybil** [comment]
Thanks a lot to all of you for your hardwork
