### ISSUE TITLE
Symfony 6 Support

### ISSUE THREAD

**Issue by natewiebe13** [php-translation/symfony-bundle#457]
This bundle doesn't currently support Symfony 6.

**Comment by crocLeMonde** [comment]
I would be grateful if a contributor is able to make this package compatible for Symfony 6

**Comment by bocharsky-bw** [comment]
Does anyone want to create a PR for this?

**Comment by bocharsky-bw** [comment]
See #464

**Comment by crocLeMonde** [comment]
That's great @bocharsky-bw thanks for this 👍, I will follow the merge of #464

**Comment by bocharsky-bw** [comment]
Sure, feel free to give a review as well ;)

**Comment by crocLeMonde** [comment]
For sure, I checked the commits then I seems ok for me as you just adapted the requirements, but I'm not informed enough on this bundle to make a judgment or to be sure about my tests

**Comment by crocLeMonde** [comment]
@bocharsky-bw as i understand now, this new requirements will be available for all when a new version tag is created, right ?

**Comment by bocharsky-bw** [comment]
yes, you're right, changes will be available in the next release, or you can use `dev-master` to try it now

**Comment by crocLeMonde** [comment]
Perfect, thanks again !
