### ISSUE TITLE
Bug: Call to a member function hasSession() on null

### ISSUE THREAD

**Issue by boksie** [php-translation/symfony-bundle#484]
Hello,

During the warming up cache of the Symfony bin/console cache:clear command, i'm getting the following error:

```
In Activator.php line 56:
                                                  
  [Error]                                         
  Call to a member function hasSession() on null 
```

The problem here is that the cache:clear is warming up the cache and calls the getSession from Activator.php, but there is no current request in the request stack.
Possible fix is to add a null check for getCurrentRequest in the Activator.php line 56.

**Comment by bocharsky-bw** [comment]
Are you on the latest version of this bundle? I see we have a null check for `getCurrentRequest()` on this line: https://github.com/php-translation/symfony-bundle/blob/4051a5be9154614807ef2e819a7fcc169dda1392/EditInPlace/Activator.php#L57

**Comment by boksie** [comment]
Thank you for your quick response, I have the latest version, but I see that in the latest tag 0.12.7 the change is not yet included.
Can you set a new tag on the bundle?

**Comment by bocharsky-bw** [comment]
I prepared a release in #485

**Comment by bocharsky-bw** [comment]
Thank you for reporting it!

Here's the new release: https://github.com/php-translation/symfony-bundle/releases/tag/0.12.8
