### ISSUE TITLE
Deprecation: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final

### ISSUE THREAD

**Issue by axi** [php-translation/symfony-bundle#490]
Since Symfony 6.1, relying on the static property "$defaultName" for setting a command name is deprecated (https://github.com/symfony/symfony/commit/ca3458c8781eafd9ff40bac50a254334e526dc10)

The replacement way is to add [Symfony\Component\Console\Attribute\AsCommand](https://github.com/symfony/console/blob/c3ebc83d031b71c39da318ca8b7a07ecc67507ed/Attribute/AsCommand.php) but php attributes are available for php8.0+ and this library supports php7.2+.

I could provide a PR for this change but that would remove support on php7.2+.
Is it wanted ? Maybe it's time to release a 1.x version ?

**Comment by axi** [comment]
![image](https://user-images.githubusercontent.com/389340/230588581-b729283a-a9b7-47ed-af0e-42f1b3441ed2.png)
![image](https://user-images.githubusercontent.com/389340/230588766-b1f25360-1ca9-447f-8c05-4383c8eff10b.png)

**Comment by rvanlaak** [comment]
The ability to use PHP attributes to configure commands was introduced in Symfony 5.3 ([see ref](https://symfony.com/doc/5.4/console.html#registering-the-command)), so fixing this deprecation would also drop support for Symfony 4.4 and requires a bump of the 5.x branch: https://github.com/php-translation/symfony-bundle/blob/master/composer.json
