### ISSUE TITLE
You have requested a non-existent service Translation\Extractor\Visitor\Php\Symfony\FormTypeChoices

### ISSUE THREAD

**Issue by byhaskell** [php-translation/symfony-bundle#508]
Hello. On symfony 6.4, I updated the composer and there were errors, I decided to return the bundles to previous versions - it did not help. That's what I stopped at and it still doesn't work.

```
"php-translation/symfony-bundle": "0.12.6",
"php-translation/common": "3.2.0",
"php-translation/extractor": "2.1.0",
"php-translation/symfony-storage": "2.3.1"
```
The error is like this even if I specify the class in services.yaml. Can the problem be solved somehow? Checked on two projects.

**Comment by bocharsky-bw** [comment]
Reverting your composer.json and composer.lock files to the previous state should help, you can just in case drop the vendor/ dir, i.e. `rm -rf vendor/` and run `composer install` again, after it things should work if they worked before the upgrade.

About the error, do you use that `FormTypeChoices` somewhere in your src/ dir? Where exactly?

**Comment by byhaskell** [comment]
@bocharsky-bw  Thank you. Tried more than once, and on two projects. Unfortunately, it doesn't work.
FormTypeChoices is only found in the vendor in your bundle.

**Comment by bocharsky-bw** [comment]
Hm, probably try to upgrade to the latest because I see you're on older versions. If still no work - you would need to do some debugging like what and where asks for that service, I'm not sure what exactly went wrong fairly speaking. Maybe someone else here will give you more tips

**Comment by byhaskell** [comment]
Surprisingly, today everything is fine on the most current version. Thank you, and sorry for the distraction.
