### ISSUE TITLE
XliffConverter does not respect default locale

### ISSUE THREAD

**Issue by prolic** [php-translation/symfony-bundle#73]
See: XliffConverter::catalogueToContent(MessageCatalogue $catalogue, $domain)

It does not set that option, and therefore in Symfony's XliffFileDumper `\Locale::getDefault()` is used

see:
```
if (array_key_exists('default_locale', $options)) {
    $defaultLocale = $options['default_locale'];
} else {
    $defaultLocale = \Locale::getDefault();
}
```

The XliffConverter should get the default_locale from the configuration and pass that here.

**Comment by Nyholm** [comment]
The Symfony Bundle does not use the `XliffConverter`. After your [PR](https://github.com/php-translation/symfony-storage/pull/8), is this still an issue?

**Comment by prolic** [comment]
No, my pr solves this, as i can push a default locale with the options now.

Am 02.02.2017 01:26 schrieb "Tobias Nyholm" <notifications@github.com>:

The Symfony Bundle does not use the XliffConverter. After your PR
<https://github.com/php-translation/symfony-storage/pull/8>, is this still
an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/php-translation/symfony-bundle/issues/73#issuecomment-276722526>,
or mute the thread

**Comment by Nyholm** [comment]
Awesome
