### ISSUE TITLE
Call to a member function getCollector() on null

### ISSUE THREAD

**Issue by prolic** [php-translation/symfony-bundle#75]
```
in vendor/php-translation/symfony-bundle/Controller/SymfonyProfilerController.php at line 152

$messages = $profile->getCollector('translation')->getMessages();
```

**Comment by Nyholm** [comment]
Thank you. Do you know why you are getting this?

I've created a PR that make sure you get a nicer error message.

**Comment by prolic** [comment]
I have to check again tomorrow.

Am 02.02.2017 01:37 schrieb "Tobias Nyholm" <notifications@github.com>:

**Comment by prolic** [comment]
Sorry I cannot remember anymore. But it must have something to do with the symfony profiler.

**Comment by toooni** [comment]
@Nyholm @prolic can't reproduce the issue yet. I will create a new issue or PR when it happens again.
