### ISSUE TITLE
Edit-in-place destroys frontend

### ISSUE THREAD

**Issue by prolic** [php-translation/symfony-bundle#76]
When I enable the edit-in-place feature, the frontend gets destroyed completely, the website is unusable. So I have to disable this feature for now. Is there anything you can do about it?

**Comment by damienalexandre** [comment]
Sure,
could you provide more informations?
Is your website using Twig? Is there any error in the browser console? Which web browser are you using? What exactly is broken?

Thanks!

**Comment by prolic** [comment]
@toooni can you provide the required feedback?

**Comment by toooni** [comment]
@damienalexandre I've created a PR with resolves this issue: https://github.com/php-translation/symfony-bundle/pull/78

**Comment by toooni** [comment]
@prolic kannst du noch das issue closen?
